version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: internship_db
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  test-db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db

  internship_fetcher:
    build: .
    command: python scripts/fetch_internships.py
    volumes:
      - .:/code
    working_dir: /code
    environment:
      PYTHONPATH: /code
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  test_postgres_data:
