"""Add company and role to reminders

Revision ID: c6aa1fa3950b
Revises: 5dd7f767dd55
Create Date: 2025-08-03 17:55:08.599986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6aa1fa3950b'
down_revision: Union[str, Sequence[str], None] = '5dd7f767dd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('company', sa.String(), nullable=False))
    op.add_column('reminders', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'role')
    op.drop_column('reminders', 'company')
    # ### end Alembic commands ###
