name: Basic CI Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Placeholder check
        run: echo "CI is working!"
