name: docker-ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: echo "DATABASE_URL=postgresql://myuser:mypassword@db:5432/internship_db" > .env

      - name: Start services
        run: docker compose up -d --build

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          until docker exec internship-support-tool-db-1 pg_isready -U myuser; do
            echo "Not ready yet..."; sleep 2;
          done

      - name: Run tests
        run: docker exec internship-support-tool-web-1 pytest
