name: CI with Docker

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: internship_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s
          --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy env example
        run: cp .env.example .env

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for db to be ready
        run: |
          echo "Waiting for Postgres to be ready..."
          for i in {1..10}; do
            docker exec internship-support-tool-db-1 pg_isready -U myuser && break
            echo "Not ready yet... ($i)"
            sleep 2
          done

      - name: Show db logs on failure
        if: failure()
        run: docker logs internship-support-tool-db-1 || true

      - name: Init DB
        run: docker exec internship-support-tool-web-1 python scripts/init_database.py

      - name: Run tests
        run: docker exec internship-support-tool-web-1 pytest
